/**
 * AI-generated case summary for pre-registration
 */
const generateCaseSummary = (emergency, patient) => {
    const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
    const severityEmoji = {
        critical: '🔴 CRITICAL',
        high: '🟠 HIGH',
        medium: '🟡 MEDIUM',
        low: '🟢 LOW'
    };

    const emergencyTypeLabel = {
        cardiac: 'Cardiac Emergency',
        trauma: 'Trauma / Injury',
        stroke: 'Stroke',
        respiratory: 'Respiratory Distress',
        burns: 'Burns',
        obstetric: 'Obstetric Emergency',
        pediatric: 'Pediatric Emergency',
        other: 'General Emergency'
    };

    return `
╔══════════════════════════════════════════════════════════╗
║       RED ALERT NETWORK – EMERGENCY CASE SUMMARY         ║
╚══════════════════════════════════════════════════════════╝

📋 CASE ID: ${emergency._id}
🕐 TIMESTAMP: ${timestamp}
⚡ SEVERITY: ${severityEmoji[emergency.severity] || emergency.severity.toUpperCase()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PATIENT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Name:         ${emergency.patientName}
Phone:        ${emergency.patientPhone || 'Not provided'}
Blood Type:   ${emergency.patientBloodType || 'Unknown'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EMERGENCY DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Type:         ${emergencyTypeLabel[emergency.emergencyType] || emergency.emergencyType}
Severity:     ${emergency.severity.toUpperCase()}
Location:     ${emergency.locationAddress || 'GPS Coordinates: ' + emergency.location.coordinates.join(', ')}
Description:  ${emergency.description || 'No additional details provided'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RECOMMENDED ACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${getRecommendedActions(emergency.emergencyType, emergency.severity)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️  PLEASE PREPARE EMERGENCY BAY IMMEDIATELY
     Patient ETA: Ambulance En Route
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by RED ALERT NETWORK – Real-Time Emergency Coordination
`.trim();
};

const getRecommendedActions = (type, severity) => {
    const actions = {
        cardiac: [
            '• Prepare cardiac catheterization lab if available',
            '• Alert cardiologist on duty',
            '• Prepare defibrillator and cardiac medications',
            '• Ready ECG equipment'
        ],
        trauma: [
            '• Activate trauma team',
            '• Prepare operating theater if critical',
            '• Ready blood transfusion supplies',
            '• Alert orthopedic/surgical team'
        ],
        stroke: [
            '• Alert neurology team',
            '• Prepare CT/MRI scanner',
            '• Ready tPA (thrombolytics) if ischemic stroke suspected',
            '• Prepare stroke unit bed'
        ],
        respiratory: [
            '• Prepare ventilator/oxygen support',
            '• Alert pulmonologist',
            '• Ready bronchodilators and respiratory medications',
            '• Prepare ICU bed if critical'
        ],
        burns: [
            '• Prepare burns unit',
            '• Ready IV fluids and pain management',
            '• Alert burns specialist',
            '• Prepare sterile dressing supplies'
        ],
        obstetric: [
            '• Alert OB/GYN team',
            '• Prepare labor and delivery room',
            '• Ready neonatal team if needed',
            '• Prepare emergency C-section if required'
        ],
        pediatric: [
            '• Alert pediatric team',
            '• Prepare pediatric emergency bay',
            '• Ready pediatric dosing equipment',
            '• Alert pediatric ICU if critical'
        ],
        other: [
            '• Prepare general emergency bay',
            '• Alert on-duty emergency physician',
            '• Ready standard emergency supplies'
        ]
    };

    return (actions[type] || actions.other).join('\n');
};

module.exports = { generateCaseSummary };
